version: "2"

services:
  ide:
    image: monstrs/cloud9
    volumes:
      - ./:/workspace
    ports:
      - "8518:80"

  npm:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: npm

  dev:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: npm start
    ports:
      - "3030:3030"
