version: "2"

services:
  ide:
    image: monstrs/cloud9
    volumes:
      - ./:/workspace
    ports:
      - "8518:80"

  install:
    image: node:7.9
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ~/yarn:/yarn
    entrypoint: yarn install

  yarn:
    image: node:7.9
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ~/yarn:/yarn
    entrypoint: yarn

  lint:
    image: node:7.9
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn run lint

  dev:
    image: node:7.9
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn start
    ports:
      - "3050:3030"
